theme: jekyll-theme-minimal
title: UEA Digital Humans
description: Research group developing algorithms to understand human speech and motion.
logo: img/uea-digital-human-group.github.io/img/UEA_NEW_BRAND_Cyan_N_A.png
